name: Pages

# 注意：需要留意thems/hexo-theme-matery/这个目录里的内容是否存在
# 如果是在themes目录下git clone hexo-theme-matery，那么push到github的内容里不包含这个目录下的内容，
# 进而会导致部署后缺失相关静态资源、博客页面打开失败。
#
# 处理方式：
# 复制文件到themes目录下，但是git无法识别到，用以下命令可以解决
# git rm -r --cached themes
#
on:
  push:
    branches:
      - master
        # - dev

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build

      - name: Deploy Github
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages # master  # gh-pages # deploying branch

      - name: deploy oss
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-hongkong.aliyuncs.com
          access-key-id: ${{ secrets.ALIYUN_ID }}
          access-key-secret: ${{ secrets.ALIYUN_SECRET }}
      - run: ossutil cp -f -u -r -j 100 --exclude ".git*" --meta=Cache-Control:max-age=86400 public/ oss://goodluck-lk/
